### ISSUE TITLE
[fix] library not installed

### ISSUE THREAD

**Issue by luisdemarchi** [albertas/deadcode#1]
After installing your library I needed to manually install "tomli" library

```
Traceback (most recent call last):
  File "/Users/luis/.pyenv/versions/lambda_poc_ai/bin/deadcode", line 5, in <module>
    from deadcode.cli import main
  File "/Users/luis/.pyenv/versions/3.10.12/envs/lambda_poc_ai/lib/python3.10/site-packages/deadcode/cli.py", line 5, in <module>
    from deadcode.actions.parse_arguments import parse_arguments
  File "/Users/luis/.pyenv/versions/3.10.12/envs/lambda_poc_ai/lib/python3.10/site-packages/deadcode/actions/parse_arguments.py", line 9, in <module>
    import tomli as tomllib
ModuleNotFoundError: No module named 'tomli'
```

**Comment by albertas** [comment]
Thanks, added the dependency in 1.1.3.

This dependency is only needed in Python versions lower than 3.11.

**Comment by albertas** [comment]
Thanks, added the dependency in 1.1.3.

This dependency is only needed in Python versions lower than 3.11.
