### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 19: character maps to <undefined>

### ISSUE THREAD

**Issue by Bouni** [albertas/deadcode#22]
When I run `deadcode.exe .` from the terminal, everything works fine

![grafik](https://github.com/user-attachments/assets/05cda166-827d-4762-a47d-e86de3dc7e1d)

But if I run the pre-commit hook I get a `UnicodeEncodeError`

```
deadcode.................................................................Failed
- hook id: deadcode
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\.cache\pre-commit\repoavu4w616\py_env-python3.12\Scripts\deadcode.EXE\__main__.py", line 7, in <module>
  File "C:\Users\user\.cache\pre-commit\repoavu4w616\py_env-python3.12\Lib\site-packages\deadcode\cli.py", line 41, in print_main
    if result := main():
                 ^^^^^^
  File "C:\Users\user\.cache\pre-commit\repoavu4w616\py_env-python3.12\Lib\site-packages\deadcode\cli.py", line 36, in main
    print('\033[1mWell done!\033[0m \u2728 \U0001f680 \u2728')
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 19: character maps to <undefined>
```

I run Windows 11 + python 3.12

Do you have an idea what's the problem?

_Originally posted by @Bouni in https://github.com/albertas/deadcode/issues/16#issuecomment-2301507705_

**Comment by Bouni** [comment]
I found a solution for this and will send a PR in a few minutes
